### ISSUE TITLE
Install as root, but oh-my-zsh only on users

### ISSUE THREAD

**Issue by antwal** [zthxxx/zsh-history-enquirer#5]
Hi

i have installed it as root (sudo), but post install not working on user

```
~ > sudo -H npm i -g zsh-history-enquirer --unsafe-perm=true                                                                                                                         at 01:47:36
Password:

> zsh-history-enquirer@1.2.2 preinstall /usr/local/lib/node_modules/zsh-history-enquirer
> command -v zsh || (npm run warn:zsh && exit 1)

/bin/zsh
/usr/local/bin/fcenquire -> /usr/local/lib/node_modules/zsh-history-enquirer/bin/index.js

> zsh-history-enquirer@1.2.2 postinstall /usr/local/lib/node_modules/zsh-history-enquirer
> env zsh -il ./scripts/postinstall.zsh


  
  Warning: cannot find oh-my-zsh, skip setup plugin for oh-my-zsh
  
  
+ zsh-history-enquirer@1.2.2
added 1 package from 1 contributor in 2.234s
```

i run after install manually 

`env zsh -il /usr/local/lib/node_modules/zsh-history-enquirer/scripts/postinstall.zsh `

but when reopen new terminal i receive this message

`[oh-my-zsh] plugin 'zsh-history-enquirer' not found`

others plugins working without problems...

the problem is on symlink of /scripts/zsh-history-enquirer.plugin.zsh here https://github.com/zthxxx/zsh-history-enquirer/blob/172688b1d4ecc2cca9c45c0e11e75a5a5530b43d/scripts/postinstall.zsh#L18

fixed manualy

```
rm .oh-my-zsh/custom/plugins/zsh-history-enquirer/zsh-history-enquirer.plugin.zsh
ln -fs /usr/local/lib/node_modules/zsh-history-enquirer/scripts/zsh-history-enquirer.plugin.zsh .oh-my-zsh/custom/plugins/zsh-history-enquirer/zsh-history-enquirer.plugin.zsh 
```

**Comment by zthxxx** [comment]
I see.

**Comment by zthxxx** [comment]
@antwal  but in this case, you don't need to install as root, just install for current user will be ok

`npm i -g zsh-history-enquirer`

if install as root, that's means use this plugin only for root

**Comment by zthxxx** [comment]
there is a new clear Debian system which I just installed it for test, 

and here is commands what I do:

```bash
sudo su -
# install nvm and node
# install on-my-zsh
whoami
npm i -g zsh-history-enquirer --unsafe-perm
zsh
# (ctrl + r)
```

![image](https://user-images.githubusercontent.com/15135943/103068161-90973780-45f7-11eb-86d3-3e535f30040c.png)

**Comment by antwal** [comment]
sorry for the delay but I've been busy, it is not for debian but for OSX Server

sudo -H is for set HOME user dir
npm packages are installed globally to all users

but not all users have oh-my-zsh installed

just correct the paths of the user folder in the script and the problem is solved; otherwise in these cases the installation does not work

thanks.

**Comment by antwal** [comment]
@zthxxx 
I'll make it easy for you, since it's the same for every POSIX system

```
#!/usr/bin/env bash

if [ $SUDO_USER ]; then user=$SUDO_USER; else user=`whoami`; fi

user_path="$(echo -n $(bash -c "cd ~${user} && pwd"))"

echo $user
echo $user_path
```

and you can retrieve the user calling sudo

**Comment by zthxxx** [comment]
@antwal  no, no, this case is **incorrect usage**, 

and the **mistake** is that you used `sudo` while install it, and you shouldn't call `postinstall` by yourself.

according to [README](https://github.com/zthxxx/zsh-history-enquirer#install),

only for root user that you need set `--unsafe-perm` option, (but in your case, obvious you want to install for your common user rather than root).

and if used without `oh-my-zsh`, there is a `manually without oh-my-zsh` section in [README](https://github.com/zthxxx/zsh-history-enquirer#manually-without-oh-my-zsh).

so, there is no need to use `sudo` at any time!

![image](https://user-images.githubusercontent.com/15135943/103187123-2aaff600-48fe-11eb-8111-e60f8242c92f.png)

**Comment by zthxxx** [comment]
I think the docs (README) in "install" section is ambiguous, and i will adjust it.

**Comment by antwal** [comment]
@zthxxx I understand that you just don't understand my problem report; but there are no problems I have created a fork and fixed the problem. Thanks anyway
